### ISSUE TITLE
failure during test time

### ISSUE THREAD

**Issue by abhishekkrthakur** [falcondai/trained-ABS-model#1]
I receive the following error when I test the trained model:

`./test_model.sh paper-example.article.txt abs-model.th 2
/home/abhishek/torch/install/bin/luajit: ./summary/beam_search.lua:103: attempt to call field 'TemporalKMaxPooling' (a nil value)
stack traceback:
    ./summary/beam_search.lua:103: in function 'generate'
    summary/run.lua:87: in function 'main'
    summary/run.lua:122: in main chunk
    [C]: in function 'dofile'
    ...ence/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00405d50
`

any pointers?

**Comment by falcondai** [comment]
should be related to https://github.com/facebook/NAMAS/issues/1

**Comment by abhishekkrthakur** [comment]
thanks for the pointer!
